pollingUrl: http://qa.smartregistries.org/all-form-submissions?timestamp=0&batch-size=100
pollingUrlUsername: demo1
pollingUrlPassword: 1

database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: password
  url: jdbc:postgresql://localhost/postgres/
  properties:
    charSet: UTF-8
  maxWaitForConnection: 5s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false

jobs:
  scanUrl: app.scheduler
  scanIntervals:
    JobScheduler: 3min

logging:
  loggers:
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: OFF
  appenders:
    - type: console
      threshold: ALL
    - type: file
      threshold: ALL
      currentLogFilename: ./logs/content_migrator.log
      archivedLogFilenamePattern: ./logs/content_migrator_%d.log.gz
      archivedFileCount: 10
      timeZone: IST
